language: go
go:
  - 1.5.4
  - 1.6.2
  - tip

env:
  global:
  - GO15VENDOREXPERIMENT='1'

before_install:
  - sudo apt-get install libgeoip-dev bzr

install:
  - mkdir -p $TRAVIS_BUILD_DIR/db
  - curl -s http://geodns.bitnames.com/geoip/GeoLiteCity.dat.gz | gzip -cd > $TRAVIS_BUILD_DIR/db/GeoIPCity.dat
  - curl -s http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz | gzip -cd > $TRAVIS_BUILD_DIR/db/GeoIPASNum.dat
  - echo [geodns] >> dns/geodns.conf
  - echo Directory=$TRAVIS_BUILD_DIR/db >> dns/geodns.conf
  - go build -v
  - go install

script:
  - cd $TRAVIS_BUILD_DIR && go test -gocheck.v
  - go test -gocheck.v -gocheck.b -gocheck.btime=2s
