language: go
sudo: required
go:
  - 1.6.3
  - 1.7.1
  - tip
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.7.1
    - IMAGE_NAME=tsuru/gandalf
addons:
  apt:
    packages:
      - rsyslog
before_script:
  - rsyslogd &
script:
  - make test
  - ./check-fmt.sh
  - go build -o build/gandalf-webserver -ldflags "-linkmode external -extldflags -static" webserver/main.go
  - go build -o build/gandalf-ssh -ldflags "-linkmode external -extldflags -static" bin/gandalf.go
services:
  - docker
  - mongodb
matrix:
  allow_failures:
    - go: tip
after_success:
  - curl https://raw.githubusercontent.com/tsuru/push-to-docker/master/push.sh | bash
