title="Hamster Config"

[author]
name="Adnaan Badr"
organization="Hamster"
email="badr.adnaan@gmail.com"


[clients]

	[clients.browser]
	ip= "127.0.0.1"
	token="mysharedtoken"
	secret="YI1ZYdopn6usnQ/5gMAHg8+pNh6D0DdaJkytdoLWUj0="
